apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 2
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: lucasrossi90/argocd:latest-v3
          ports:
            - containerPort: 8080